### PR TITLE
Update fsevent dependencies

### PR DESCRIPTION
**Pull request by Eijebong**
This will dedupe quite a few dependencies in crates using notify. I didn't bump the version because I don't know if any breaking change mad it to the branch but I'd be more than happy to do so if you want

### CODE REVIEW

**Comment by passcod** [comment]
Is this a WIP? It doesn't build at all.

**Comment by Eijebong** [comment]
Weird, it built for me on linux and macos, I'll have a look

**Comment by Eijebong** [comment]
Ok, that's funy, it doesn't fail on macos but it fails if I cross compile from linux... i'll fix this

**Comment by passcod** [comment]
Does the test suite fail for you locally? I'll retry the run in CI to see if it's intermittent anyway.

Otherwise, looks good. That will get into 5.0.

For the current major, would you be willing to also write this for the `try-v4` branch I just pushed? That way I'd do a patch release immediately.

**Comment by Eijebong** [comment]
This looks intermittent. Was it already like that before ? Maybe some time behavior changed and needs adjustment ?

**Comment by passcod** [comment]
Fsevents tests are awful and often intermittent, this is known :)

**Comment by Eijebong** [comment]
Ok, I'll make a PR against the `try-v4 branch` too then

**Pull request merged**
