### PR TITLE
[WIP] Implement poll watcher

### PR DESCRIPTION
**Pull request by dfaust**
I started implementing the poll watcher. There's still a lot missing, but it passes all existing tests.

As discussed in #142, the code is quite ugly. In addition to a tree, that holds all files and directories, there is an `ancestors` vector that holds the children of all parent directories while traversing the fs using walkdir. It will be used to detect deletes.

There are still some bigger problems:
- The poll watcher needs an `interval` parameter. It's currently set to 20ms so the tests can succeed.
- Stopping the poll thread is problematic. It currently checks for a shutdown signal once every iteration of the main loop. This is too slow, especially if the `interval` is very high.

### CODE REVIEW

**Comment by passcod** [comment]
For the second issue, how about this:

- Instead of `sleep`, use `park_timeout_ms`
- Store the thread Handle on the Backend
- When the Backend Drops, tell the channel to shutdown, then unpark the thread

That should get rid of the wait without having a tiny loop interval.

**Comment by SirVer** [comment]
@dfaust Thanks for putting so much work in improving notify! Félix made it excellent already, but your redesign looks super clean right now and I am excited about all the new features!

**Comment by dfaust** [comment]
Well, as you already noticed, I didn't do the re-design, that's all @passcod's work.

**Comment by passcod** [comment]
I'll merge this soonish to bring it within the main tree and bring it to the newest interface, which I believe might neatly solve some of its issues.

**Pull request merged**
